# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
# Comprehensive example: https://github.com/executablebooks/jupyter-book/blob/master/docs/_config.yml

title: python-conflux-sdk
author: Read the Docs team
logo: ../logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/conflux-chain/python-conflux-sdk  # Online location of your book
  path_to_book: docs/en  # Optional path to your book, relative to the repository root
  branch: dev  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.napoleon'
  # - 'sphinx.ext.autosummary'
  config:
    # autosummary_generate: True
    autoclass_content: "both"
    copyright: "2023"
